name: build-and-run hello-kube

on:
  push:
    branches: [ main ]

permissions:
    id-token: write
    contents: read
    
jobs:
  build-run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: get github action OIDC token
        run: |
          TOKEN=$(curl -s -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=kubernetes" \
            | jq -r '.value')
            
          echo "OIDC_TOKEN=$TOKEN" >> $GITHUB_ENV
      
      - name: Check docker
        run: docker info

      - name: Build image
        run: |
          docker build -t hello-kube ./hello-kube
      
      - name: Run container
        run: |
          docker run --rm -e KUBE_TOKEN="${KUBE_TOKEN}" hello-kube